---
- name: install "{{ package_name }}" service
  yum:
    name: "{{ package_name }}"
    state: latest

- name: Enable service "{{ package_name }}"
  service: name= "{{ package_name }}"  enabled=yes state=started
...
