---
- hosts: all
  tasks:
  - name: Disable service NM
    service:
      name: NetworkManager
      enabled: no
      state: stopped

  - name: Changing parametrs in "/etc/default/grub" net.ifnames=0
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX='
      line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0 crashkernel=auto rd.lvm.lv=centos_control/root rd.lvm.lv=centos_control/swap rhgb quiet"'

  - name: Reload GRUB 
    command: grub2-mkconfig 

...
